MAX_LENGTH_EMAILFIELD = 254
MAX_LENGTH_CHARFIELD = 256
MAX_LENGTH_CHARFIELD_NAME = 150
MAX_LENGTH_CHARFIELD_ROLE = 20
MAX_LENGTH_CHARFIELD_CODE = 255
MAX_LENGTH_TEXTFIELD = 256
MAX_LENGTH_SLUGFIELD = 50
