MAX_LENGTH_EMAILFIELD = 254
MAX_LENGTH_CHARFIELD = 256
MAX_LENGTH_CHARFIELD_NAME = 150
MAX_LENGTH_CHARFIELD_ROLE = 20
MAX_LENGTH_TEXTFIELD = 256
MAX_LENGTH_SLUGFIELD = 50
MIN_VALUE_SCORE = 0
MAX_VALUE_SCORE = 10
