# Generated by Django 3.2 on 2024-11-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_rating'),
        ('reviews', '0005_auto_20241118_1558'),
    ]

    operations = [
    ]
