# Generated by Django 3.2 on 2024-11-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_merge_0002_alter_title_rating_0005_auto_20241118_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
